### ISSUE TITLE
Doesn't work on self-hosted Gitlab

### ISSUE THREAD

**Issue by ThePlenkov** [docker/dev-envs-extension#1]
Hi!

Unfortunately this extension doesn't work on self-hosted Gitlab.

Any plans to implement this?

Thanks!

**Comment by ThePlenkov** [comment]
OK, i've checked the extension and noticed that is not even loaded. In settings i see this:
![image](https://user-images.githubusercontent.com/6381507/206664170-d6da60a7-c3b5-4baa-a862-7c8ecb03402a.png)

But problem is - you expect the self-hosted site to be domain.gitlab.com while we have our instance on gitlab.domain.com

So it'd be nice to have an option to control this somehow.

Thanks!

**Comment by laurazard** [comment]
Sorry we missed that! Thanks for the PR, I went and merged it and we'll get it into the next release 🥳
